export const data = [
  {
    id: 1,
    img: 'https://react-vite-projects-5-menu.netlify.app/images/item-1.jpeg',
    category: 'Break fast',
    title: 'Buttermilk Pancakes',
    price: '$15.99',
    decs: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed',`,
  },
  {
    id: 2,
    img: 'https://react-vite-projects-5-menu.netlify.app/images/item-4.jpeg',
    title: 'Country Delight',
    category: 'Break fast',
    price: '$20.99',
    decs: 'Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut,',
  },
  {
    id: 3,
    img: 'https://react-vite-projects-5-menu.netlify.app/images/item-7.jpeg',
    title: 'Bacon Overflow',
    category: 'Break fast',
    price: '$8.99',
    decs: ' carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird',
  },
  {
    id: 4,
    img: 'https://react-vite-projects-5-menu.netlify.app/images/item-2.jpeg',
    category: 'Programming',
    price: '₹7,999.00',
    decs: ' A data analyst gathers, cleans, and studies data sets to help solve problems. ... A data analyst collects,cleans, and interprets data sets in order to answer a question or solvea problem.',
  },
  {
    id: 5,
    img: 'https://react-vite-projects-5-menu.netlify.app/images/item-5.jpeg',
    category: 'Programming',
    price: '₹7,999.00',
    decs: ' A data analyst gathers, cleans, and studies data sets to help solve problems. ... A data analyst collects,cleans, and interprets data sets in order to answer a question or solvea problem.',
  },
  {
    id: 6,
    img: 'https://react-vite-projects-5-menu.netlify.app/images/item-8.jpeg',
    category: 'Web development',
    price: '₹7,999.00',
    decs: ' A data analyst gathers, cleans, and studies data sets to help solve problems. ... A data analyst collects,cleans, and interprets data sets in order to answer a question or solvea problem.',
  },
  {
    id: 7,
    img: 'https://react-vite-projects-5-menu.netlify.app/images/item-3.jpeg',
    category: 'Web development',
    price: '₹7,999.00',
    decs: ' A data analyst gathers, cleans, and studies data sets to help solve problems. ... A data analyst collects,cleans, and interprets data sets in order to answer a question or solvea problem.',
  },
  {
    id: 8,
    img: 'https://react-vite-projects-5-menu.netlify.app/images/item-6.jpeg',
    category: 'Web development',
    price: '₹7,999.00',
    decs: ' A data analyst gathers, cleans, and studies data sets to help solve problems. ... A data analyst collects,cleans, and interprets data sets in order to answer a question or solvea problem.',
  },
];
